# Generated by Django 4.0.4 on 2022-05-10 21:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('filme', '0002_usuario'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Usuario',
        ),
    ]
