# Generated by Django 4.0.4 on 2022-05-10 22:12

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('filme', '0003_delete_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filme',
            name='data_criacao',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 10, 22, 12, 48, 470475, tzinfo=utc)),
        ),
    ]
