# Generated by Django 4.0.4 on 2022-05-10 22:13

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('filme', '0004_alter_filme_data_criacao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filme',
            name='data_criacao',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
